# Generated by Django 5.0.1 on 2024-10-11 07:00

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=backend.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
